### ISSUE TITLE
Allow more control over event debug output

### ISSUE THREAD

**Issue by squattingmonk** [squattingmonk/nwn-core-framework#2]
There's currently a switch in `core_c_config.nss` that lets the user set an alternate debug level for heartbeat scripts. This helps cut down on extra noise. But there are other events that cause a lot of noise (e.g., OnCreaturePerception). It would be nice to allow builders to set module-level event debug levels and to allow those settings to be overridden on a per-object basis.

**Comment by tinygiant98** [comment]
See comments for PR. #5
