### ISSUE TITLE
FindListItem not carrying over parsed item count

### ISSUE THREAD

**Issue by tinygiant98** [squattingmonk/nwn-core-framework#3]
In util_i_csvlists.nss, FindListItem is not carrying over the parsed item count when the item being searched for is also a substring of a previous item (i.e. the previous item count is not being carried through the recursion).  
![debugnofix](https://user-images.githubusercontent.com/56231301/80591344-8e8ac380-89eb-11ea-96e7-bca88814a47b.JPG)
As you can see in this screenshot from a Debug() call, the system should find "emote" at index 7 in the passed list, but it finds it at index 2.  This is because of the matching substring in "pc_emote" at index 4.  During the recursion call, nOffset resets to zero and the item "server" is counted as index 0 with "emote" ending up at index 2.

Moving the "emote" item to a position before the "pc_emote" item fixes the problem, but it's not the best solution.  Carrying the previous item count (number of items parsed before recursion) fixes the issue as you can see in the following screenshot.
![debugfix](https://user-images.githubusercontent.com/56231301/80591618-fccf8600-89eb-11ea-8781-cdad1acca710.JPG)

Following are the code changes that fix the issue, however I don't know if any other functions in util_i_csvlists or util_i_lists work the same way.  If so, they may need attention.

Prototype:
```c
int FindListItem(string sList, string sListItem, int nParsed = 0);
```

Body:
```c
int FindListItem(string sList, string sListItem, int nParsed = 0)
{
    // Sanity check.
    if (sList == "" || sListItem == "") return -1;

    // Is the item even in the list?
    int nOffset = FindSubString(sList, sListItem);
    if (nOffset == -1) return -1;

    // Quickest way to find it: count the commas that occur before the item.
    int i = GetSubStringCount(GetStringLeft(sList, nOffset), ",");

    // Make sure it's not a partial match.
    if (GetListItem(sList, i) == sListItem)
        return i + nParsed;

    // Okay, so let's slim down the list and re-execute.
    string sParsed = StringParse(sList, GetListItem(sList, ++i));
    return FindListItem(StringRemoveParsed(sList, sParsed), sListItem, i + nParsed);
}

**Comment by tinygiant98** [comment]
Just realized you might need to send  `i + nParsed` instead of `i` on the last line to carry through multiple recursion, should that occur, but haven't tested it yet.

**Comment by squattingmonk** [comment]
Thanks! I added your fix, but within a private function to preserve the public interface.
