### ISSUE TITLE
Breaking Changes

### ISSUE THREAD

**Issue by tinygiant98** [squattingmonk/nwn-core-framework#37]
Not necessarily actual issues, just wanted document breaking changes in the framework when plugged into a module that currently uses it as a base.  ***This is not a request to make any changes to the new version, just documentation.***

`RegisterEventScripts()` no longer exists and is replaced with `RegisterEventScript()`.  It's likely that multiple scripts were never assigned at the same time, anyway, so no big deal, but all plugins created until the old version will have to be updated with the new function name.

`core_i_database` no longer exists and is not replaced.  This breaks the administration system that used the database for player registration.  Custom functions will have to be used to structure and populate the player database.  Probably needed to be done anyway.

Several changes to the way plugins are handled, which is mostly internal to the framework, except `SetPluginLibraries()` no longer exists and has been replaced by setting a local string on the plugin object during plugin creation (or call `LoadLibraries()` during plugin creation.  Also, `GetPlugin()` no longer utilizes the creation shortcut if the plugin isn't found.  Code must be modified to explicity create the plugin object using `CreatePlugin()`.

`GetCurrentEvent()` now returns a string instead of an object.  Generally a simple fix since most `GetCurrentEvent()` calls were used just to get the event name.

`DelayLibraryScript()` has been removed and not replaced.  The removes the ability to delay running library scripts.  This was only used in a single test script, so easy fix.

`GetEventTriggeredBy()` can no longer accept an object parameter.

`[Get|Set|Clear]EventState()` can no longer accept an object parameter.

`GetWasPC()` has been removed, but likely unused anyway, expect in `hook_nwn`

Line 308 needs to look for NCS instead of NSS, sumbit PR.

**Comment by tinygiant98** [comment]
`CreateTimer()` now accepts jitter as a float instead of the previous int.

**Comment by squattingmonk** [comment]
As of eceb723, timers have been moved to [sm-utils](https://github.com/squattingmonk/sm-utils). That implementation now executes a script instead of an event. Functions that were previously using `CreateTimer()` to run events should update to use `CreateEventTimer()`.
