### ISSUE TITLE
RemoveScriptSource not working in OnAreaExit?

### ISSUE THREAD

**Issue by tinygiant98** [squattingmonk/nwn-core-framework#39]
Haven't delved into this too far yet, so I'm putting this here as a marker for future investigation, but I noticed this today while doing some testing.  I added a henchman by script to the area with `CreateObject`.  The correct events fired and the object was added as a script source as defined in OnAreaEnter:
![image](https://user-images.githubusercontent.com/56231301/192124636-52c6ea0d-28b0-4700-9f21-5b8e04398c90.png)

However, when I removed the creature programmatically (DestroyObject), the OnAreaExit event triggered for the removed creature, but it doesn't appear that the creature object was available to the exit event script.
![image](https://user-images.githubusercontent.com/56231301/192124671-f09a9cb7-5a59-48ff-87c2-a38c4cbe42db.png)
I have a feeling that it's because the object was destroyed and not just departed the area.  Again, no action required, this is just a bookmark.

**Comment by squattingmonk** [comment]
When the object is destroyed, it is no longer valid, but it does still have an ID which is removed from the database. I have updated [sm-utils](https://github.com/squattingmonk/sm-utils/commit/340dc07872c366e53891a1d0f1dd3accaf1cf457) to show the object id as its prefix if the object is not valid.
